// Generated by CoffeeScript 1.6.3
(function() {
  var Plugin;

  Plugin = (function() {
    Plugin = function(bot) {
      this.name = "mime";
      this.title = "mime";
      this.description = "Example CoffeeScript mime.";
      this.version = "0.1";
      this.author = "Luke Strickland";
      this.bot = bot;
      return this.client = bot.client;
    };
    Plugin.prototype.onMessage = function(from, to, message) {
      return this.client.say((to.substr(0, 1) === "#" ? to : from), message);
    };
    return Plugin;
  })();

  exports.Plugin = Plugin;

}).call(this);
